# Generated by Django 5.0 on 2025-11-07 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapApp', '0002_chat_mensaje_trueque_chat_trueque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=300)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
