# Generated by Django 5.0 on 2025-11-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapApp', '0003_alter_trueque_solicitante_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
